#!/usr/bin/env python
# encoding: utf-8

import sys, rospy
from pimouse_ros.msg import LightSensorValues

def get_freq():
    f = rospy.get_param('lightsensors_freq', 10)
    try:
        if f <= 0.0:
            raise Exception()
    except:
        rospy.logerr("value error: lightsensors_freq")
        sys.exit(1)
    return f

if __name__ == '__main_':
    devfile = '/dev/rtlightsensor0'

    rospy.init_node('lightsensors')
    pub = rospy.Publisher('lightsensors', LightSensorValues, queue_size=1)

    freq = get_freq()
    rate = rospy.Rate(freq)

    while not rospy.is_shutdown():
        try:

        except:
            rospy.logerr("cannot open " + devfile)

        f = get_freq()
        if f != freq:
            freq = f
            rate = rospy.Rate(freq)

        rate.sleep()

